server:
  port: ${port:10090}
spring:
  application:
    name: quickstart-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.222.21:8848,192.168.222.21:8849,192.168.222.21:8850
