server:
  port: 80
spring:
  application:
    name: quickstart-consumer
  cloud:
    nacos:
      discovery:
#        server-addr: 192.168.222.21:8848,192.168.222.22:8848,192.168.222.23:8848
        server-addr: 192.168.222.21:8848
        username: nacos
        password: nacos